language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t flofloninja/frontend -f  Dockerfile.dev .

script:
  - docker run -e CI=true flofloninja/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-438306072208"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
